title: Omar Ragab Ali

logo: /profile/photo.jpg

description: Learn actionable strategies to drive decisions and innovation. Perfect for professionals eager to master data-driven success in a fast-paced world.

theme: jekyll-theme-minimal

show_downloads: false
github:
  is_project_page: false

  footer: _includes/footer.html


